name: PL-SQL Autograding

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Student Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Autograder
        run: python autograder/grade.py
